- name: Add cmdline params to allow Docker to read RAM usage
  ansible.builtin.lineinfile:
    path: "{{ cmdline_file_path }}"
    regexp: '^(?!.*?{{ item }})(.*)$'
    line: '\1 {{ item }}'
    backrefs: true
  loop: "{{ cmdline_params }}"
  notify:
    - Reboot