- name: Set static IP
  template:
    src: dhcpcd.j2
    dest: "{{ dhcpcd_file_path }}"
    mode: "0644"
  # when: dhcpcd is defined
  # notify: restart dhcpcd

## reboot and wait for connection on new IP with port 22