- name: Set ssh key
  ansible.posix.authorized_key:
    user: "{{ ssh.username }}"
    state: present
    key: "{{ lookup('file', '{{ ssh.key_path }}') }}"

- name: Disallow password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: Disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - Reboot
    - Restart SSH