dhcphomeserver:
  hosts:
    dhcp_debian_container:
      ansible_host: localhost
      ansible_ssh_pass: 123

homeserver:
  hosts:
    debian_container:
      ansible_host: localhost
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"

local:
  hosts:
    local_machine:
      ansible_host: localhost
      ansible_connection: local

all:
  vars:
    ansible_connection: ssh
    ansible_become_password: 123
    ansible_user: testuser
    ansible_port: 2222