dhcphomeserver:
  hosts:
    localhost:
      ansible_ssh_pass: 123

homeserver:
  hosts:
    127.0.0.1:
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"

all:
  vars:
    ansible_connection: ssh
    ansible_become_password: 123
    ansible_user: testuser
    ansible_port: 2222