dhcphomeserver:
  hosts:
    localhost:
      # ansible_connection: local
      ansible_connection: ssh
      ansible_become_password: 123
      ansible_user: testuser
      ansible_ssh_pass: 123
      ansible_port: 2222

homeserver:
  hosts:
    127.0.0.1:
      ansible_connection: ssh
      ansible_become_password: 123
      ansible_user: testuser
      ansible_ssh_private_key_file: "~/.ssh/raspiviseu_rsa"
      ansible_port: 2222
